version: '2.1'

services:
  ms_authentication:
    image: ms_authentication
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8081:8081
      - 5005:5005
    