version: '2.1'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8050:8050
      - 5005:5005
    