version: '2.1'

services:
  proizvodnja:
    image: proizvodnja
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8084:8084
      - 5005:5005
    